apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
  labels:
    app: ecomm-app
    
spec:
  selector:
    app: ecomm-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
~
