---
- hosts: localhost
  tasks:
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:http://34.216.135.93:8081/artifactory/libs-release-local/org/springframework/samples/spring-petclinic/4.2-RELEASE/spring-petclinic-4.2-RELEASE.war
      url: 
      dest: /opt
      url_username: admin
      url_password: admin123





  - name: Build image and with build args
    docker_image:
      name: petclinicweb
      build:
        path: /opt
        pull: no
        args:
          listen_port: 8888
      source: build

  - name: Log into DockerHub
    docker_login:
     username: cicdcontainer
     password: hello_hello@1234.


  - name: Push to docker hub
    docker_image:
      name: petclinicweb
      repository: cicdcontainer/webappproject:1.0
      push: yes
      source: local
